
 baseURL=https://demo.guru99.com/v4/
 username=mngr434398
 password=byhEpar
 chromepath=C:\\Users\\ANIL\\eclipse-workspace\\inetBankingV1\\Drivers\\chromedriver.exe
 edgepath=C:\\Users\\ANIL\\eclipse-workspace\\inetBankingV1\\Drivers\\msedgedriver.exe
 firefoxpath=C:\\Users\\ANIL\\eclipse-workspace\\inetBankingV1\\Drivers\\geckodriver.exe